package com.spindle.core.minecraft.hook.patch;

import java.util.List;

public record MinecraftHookPatchPlan(
    int schema,
    String milestoneName,
    String target,
    String minecraftVersion,
    String side,
    String catalogId,
    boolean sourceContractValidationPassed,
    int sourceContractErrorCount,
    String minecraftMainClass,
    boolean gatePassed,
    String gateFailureReason,
    boolean patchPlanningSucceeded,
    boolean patchPlanned,
    int plannedPatchCount,
    MinecraftHookPatchEligibility patchEligibility,
    String selectedPlacementId,
    Integer selectedBytecodeAnalysisSchema,
    String selectedBytecodeAnalysisMilestone,
    String targetClass,
    String targetMethod,
    String targetDescriptor,
    Integer originalCodeLength,
    Integer plannedCodeLength,
    Integer codeLengthDelta,
    String originalCodeSha256,
    Integer insertionOffset,
    boolean insertionInstructionBoundary,
    Integer insertBeforeOriginalInstructionOffset,
    String insertedInstructionHex,
    List<MinecraftPatchConstantPoolRequirement> requiredConstantPoolEntries,
    boolean constantPoolRewriteRequired,
    boolean codeRewriteRequired,
    boolean maxStackRewriteRequired,
    boolean maxLocalsRewriteRequired,
    boolean exceptionTableRewriteRequired,
    boolean stackMapTableRewriteRequired,
    boolean nestedCodeAttributeRewriteRequired,
    boolean lineNumberTableRewriteRequired,
    boolean localVariableTableRewriteRequired,
    boolean branchOffsetRewriteRequired,
    boolean switchOffsetRewriteRequired,
    boolean transformReadyForFixtureOnly,
    boolean transformReadyForMinecraftRuntime,
    boolean codeAttributeParsed,
    boolean instructionInspectionOccurred,
    boolean patchPlanningOccurred,
    boolean injectionOccurred,
    boolean transformationOccurred,
    boolean patchingOccurred,
    boolean bytecodeModified,
    boolean javaAgentUsed,
    boolean mixinUsed,
    boolean remappingOccurred,
    boolean publicApiExposed,
    boolean javaModExecutionSandboxed,
    MinecraftPatchOffsetAdjustmentSummary branchTargetAdjustmentSummary,
    MinecraftPatchOffsetAdjustmentSummary switchTargetAdjustmentSummary,
    MinecraftPatchExceptionTableImpact exceptionTableImpact,
    MinecraftPatchStackMapImpact stackMapImpact,
    MinecraftPatchNestedAttributeImpact nestedAttributeImpact,
    List<MinecraftPlannedHookPatch> plannedPatches) {
  public MinecraftHookPatchPlan {
    requiredConstantPoolEntries =
        List.copyOf(requiredConstantPoolEntries == null ? List.of() : requiredConstantPoolEntries);
    plannedPatches = List.copyOf(plannedPatches == null ? List.of() : plannedPatches);
  }
}
