package com.spindle.core.minecraft.registry;

public enum MinecraftRegistryAccessStrategy {
  NONE,
  CLASS_REFERENCE_ONLY,
  STATIC_METHOD_BOUNDARY_ANALYSIS_REQUIRED,
  INSTANCE_METHOD_RECEIVER_CAPTURE_REQUIRED,
  STATIC_FIELD_ACCESS_REQUIRED,
  INSTANCE_FIELD_OWNER_CAPTURE_REQUIRED
}
