package com.spindle.core.minecraft.registry;

public enum MinecraftRegistryRepresentationKind {
  UPSTREAM_RESOURCE_RELOAD_ARC_DECISION,
  TARGET1_INTERPRETED_METADATA,
  FUTURE_REGISTRY_BOOTSTRAP_PHASE,
  FUTURE_REGISTRY_ACCESS,
  FUTURE_REGISTRY_KEY_MODEL,
  FUTURE_CONTENT_REGISTRATION_PHASE,
  FUTURE_REGISTRY_MUTATION_OPERATION,
  FUTURE_DYNAMIC_REGISTRY_RELOAD_LINK
}
