package com.spindle.core.minecraft.concept;

public enum MinecraftTargetConceptFamily {
  SERVER_LIFECYCLE,
  COMMAND_REGISTRATION,
  DATA_RESOURCES_RELOAD,
  REGISTRY_BOOTSTRAP,
  SERVER_TICK_SCHEDULING,
  WORLD_CHUNK_PERSISTENCE,
  ENTITY_PLAYER_GAMEPLAY,
  NETWORKING_PACKETS,
  ATTACHABLE_STATE,
  CONTROLLED_ACCESS_BRIDGES
}
