package com.spindle.core.minecraft.hook.bootstrap;

public record MinecraftBootstrapHookTransformationResult(
    int schema,
    String milestoneName,
    MinecraftBootstrapHookTransformationMode transformationMode,
    String scope,
    MinecraftBootstrapHookTransformationStatus status,
    MinecraftBootstrapHookTransformationGate gate,
    String sourcePatchId,
    String sourcePlacementId,
    String sourceContractId,
    String targetBinaryName,
    String targetInternalName,
    String targetMethod,
    String targetDescriptor,
    String dispatcher,
    String originalClassSha256,
    String transformedClassSha256,
    String originalCodeSha256,
    String transformedCodeSha256,
    Integer originalCodeLength,
    Integer transformedCodeLength,
    Integer constantPoolCountBefore,
    Integer constantPoolCountAfter,
    Integer methodrefIndex,
    boolean bootstrapTransformationEnabled,
    boolean runtimeClassLoaderTransformationEnabled,
    boolean fakeServerRuntimeTransformed,
    boolean realMinecraftRuntimeTransformed,
    boolean transformationOccurred,
    boolean patchingOccurred,
    boolean bytecodeModified,
    boolean publicApiExposed,
    boolean javaAgentUsed,
    boolean mixinUsed,
    boolean remappingOccurred,
    boolean accessWidenersUsed,
    boolean javaModExecutionSandboxed,
    int dispatcherInvocationCount,
    boolean dispatcherInvocationObserved,
    boolean minecraftMainInvoked,
    String fixtureTransformationStatus,
    String fixtureTransformationFailureReason,
    String failureReason,
    byte[] transformedClassBytes) {
  public MinecraftBootstrapHookTransformationResult {
    transformedClassBytes = transformedClassBytes == null ? null : transformedClassBytes.clone();
  }
}
