package com.spindle.core.minecraft.hook.transform;

public record SteelHookMethodExitRewriteResult(
    SteelHookMethodExitRewriteStatus status,
    String failureReason,
    SteelHookMethodExitRewriteRequest request,
    String originalClassSha256,
    String transformedClassSha256,
    String originalCodeSha256,
    String transformedCodeSha256,
    Integer originalCodeLength,
    Integer transformedCodeLength,
    Integer constantPoolCountBefore,
    Integer constantPoolCountAfter,
    Integer methodrefIndex,
    String insertedInstructionHex,
    boolean methodExitTransformationOccurred,
    boolean bytecodeModified,
    boolean transformedClassBytesProduced,
    boolean stackMapTablePresent,
    boolean stackMapTableRewriteSupported,
    boolean stackMapTableRewriteApplied,
    boolean exceptionTablePresent,
    boolean branchRewriteRequired,
    boolean switchRewriteRequired,
    Integer normalReturnOpcodeCount,
    Integer insertionCount,
    SteelHookMethodExitConstantPoolPatch constantPoolPatch,
    SteelHookMethodExitCodePatchResult codePatch,
    SteelHookMethodExitTransformedClass transformedClass) {}
