package com.spindle.core.minecraft.command;

import com.spindle.core.minecraft.MinecraftSide;

public record MinecraftCommandDispatcherBindingAnalysis(
    int schema,
    String milestoneName,
    String target,
    String minecraftVersion,
    MinecraftSide side,
    String conceptId,
    String sourceCommandDispatcherSymbolAnalysisMilestone,
    String commandBoundaryId,
    boolean analysisOnly,
    boolean classLoadingOccurred,
    boolean injectionOccurred,
    boolean transformationOccurred,
    boolean patchingOccurred,
    boolean hookInstallationOccurred,
    boolean runtimeDispatchOccurred,
    boolean commandRegistrationOccurred,
    boolean commandExecutionOccurred,
    boolean commandDispatcherAccessOccurred,
    boolean publicApiExposed,
    boolean javaModExecutionSandboxed,
    boolean sourceSymbolGatePassed,
    String sourceSelectionStatus,
    boolean sourceMinimalCommandRegistrationProofEligible,
    boolean gatePassed,
    String gateFailureReason,
    MinecraftCommandDispatcherBindingStatus bindingStatus,
    MinecraftCommandDispatcherAccessStrategy accessStrategy,
    String selectedCandidateId,
    String selectedCandidateKind,
    String ownerInternalName,
    String memberName,
    String descriptor,
    boolean staticMember,
    boolean requiresDispatcherValueCapture,
    boolean requiresOwnerInstanceCapture,
    boolean requiresFieldAccess,
    boolean requiresFutureSteelHookPrimitive,
    boolean currentSteelHookMethodEntryCompatible,
    boolean minimalCommandRegistrationProofRecommended,
    String nextRecommendedAction,
    String notes) {}
