package com.spindle.core.minecraft.hook.steelhook;

public enum SteelHook04RejectionReason {
  SOURCE_STEELHOOK_03_NOT_COMPLETE("SOURCE_STEELHOOK_03_NOT_COMPLETE"),
  UNSUPPORTED_PRIMITIVE_KIND("UNSUPPORTED_PRIMITIVE_KIND"),
  PUBLIC_API_LEAKAGE("PUBLIC_API_LEAKAGE"),
  RAW_BYTE_PAYLOAD_PRESENT("RAW_BYTE_PAYLOAD_PRESENT"),
  UNSUPPORTED_FIXTURE_SHAPE("UNSUPPORTED_FIXTURE_SHAPE"),
  MALFORMED_PRIMITIVE_PLAN("MALFORMED_PRIMITIVE_PLAN"),
  WRONG_OWNER("WRONG_OWNER"),
  WRONG_NAME("WRONG_NAME"),
  WRONG_DESCRIPTOR("WRONG_DESCRIPTOR"),
  WRONG_OPCODE("WRONG_OPCODE"),
  NO_MATCHING_CALLSITE("NO_MATCHING_CALLSITE"),
  AMBIGUOUS_MULTIPLE_CALLSITES("AMBIGUOUS_MULTIPLE_CALLSITES"),
  CONSTRUCTOR_OR_SPECIAL_INVOKE_UNSUPPORTED("CONSTRUCTOR_OR_SPECIAL_INVOKE_UNSUPPORTED"),
  BRANCH_REWRITE_REQUIRED("BRANCH_REWRITE_REQUIRED"),
  SWITCH_REWRITE_REQUIRED("SWITCH_REWRITE_REQUIRED"),
  EXCEPTION_TABLE_PRESENT("EXCEPTION_TABLE_PRESENT"),
  STACKMAP_FRAME_RECOMPUTATION_REQUIRED("STACKMAP_FRAME_RECOMPUTATION_REQUIRED"),
  SYNCHRONIZED_METHOD_UNSUPPORTED("SYNCHRONIZED_METHOD_UNSUPPORTED"),
  CLASS_INITIALIZER_UNSUPPORTED("CLASS_INITIALIZER_UNSUPPORTED"),
  RUNTIME_CLASSLOADING_ATTEMPTED("RUNTIME_CLASSLOADING_ATTEMPTED"),
  HOOK_INSTALLATION_ATTEMPTED("HOOK_INSTALLATION_ATTEMPTED"),
  DISPATCHER_EXECUTION_ATTEMPTED("DISPATCHER_EXECUTION_ATTEMPTED"),
  MINECRAFT_EXECUTION_ATTEMPTED("MINECRAFT_EXECUTION_ATTEMPTED");

  private final String id;

  SteelHook04RejectionReason(String id) {
    this.id = id;
  }

  public String id() {
    return id;
  }
}
