package com.spindle.core.minecraft.hook.steelhook;

public enum SteelHook04FixtureShape {
  RETURN_SINGLE_PRIMITIVE_VALUE("RETURN_SINGLE_PRIMITIVE_VALUE"),
  RETURN_SINGLE_REFERENCE_VALUE("RETURN_SINGLE_REFERENCE_VALUE"),
  INVOKE_SINGLE_STATIC_OR_VIRTUAL_CALLSITE("INVOKE_SINGLE_STATIC_OR_VIRTUAL_CALLSITE"),
  CONSTRUCTOR_INVOCATION("CONSTRUCTOR_INVOCATION"),
  SPECIAL_INVOCATION("SPECIAL_INVOCATION"),
  MULTIPLE_MATCHING_CALLSITES("MULTIPLE_MATCHING_CALLSITES"),
  BRANCHING_METHOD("BRANCHING_METHOD"),
  SWITCH_METHOD("SWITCH_METHOD"),
  EXCEPTION_TABLE_METHOD("EXCEPTION_TABLE_METHOD"),
  SYNCHRONIZED_METHOD("SYNCHRONIZED_METHOD"),
  CLASS_INITIALIZER("CLASS_INITIALIZER"),
  FRAME_RECOMPUTATION_REQUIRED("FRAME_RECOMPUTATION_REQUIRED");

  private final String id;

  SteelHook04FixtureShape(String id) {
    this.id = id;
  }

  public String id() {
    return id;
  }
}
