package com.spindle.core.minecraft.resource;

import com.spindle.core.minecraft.MinecraftSide;
import java.util.List;

public record MinecraftResourceReloadArcDecisionAnalysis(
    int schema,
    String milestoneName,
    String target,
    String minecraftVersion,
    MinecraftSide side,
    String conceptId,
    String sourceResourceReloadAnalysisMilestone,
    String sourceResourceReloadSymbolAnalysisMilestone,
    String sourceResourceReloadBindingAnalysisMilestone,
    String sourceResourceVisibilityGenerationAnalysisMilestone,
    boolean analysisOnly,
    boolean classLoadingOccurred,
    boolean injectionOccurred,
    boolean transformationOccurred,
    boolean patchingOccurred,
    boolean hookInstallationOccurred,
    boolean runtimeDispatchOccurred,
    boolean resourceReloadOccurred,
    boolean resourceAccessOccurred,
    boolean datapackAccessOccurred,
    boolean dataGenerationOccurred,
    boolean generatedFileWriteOccurred,
    boolean registryBootstrapOccurred,
    boolean registryMutationOccurred,
    boolean publicApiExposed,
    boolean javaModExecutionSandboxed,
    boolean sourceResourceReloadGatePassed,
    boolean sourceSymbolGatePassed,
    String sourceSymbolDiscoveryStatus,
    boolean sourceBindingGatePassed,
    String sourceBindingStatus,
    boolean sourceBindingReloadProofRecommended,
    boolean sourceBindingCurrentSteelHookMethodEntryCompatible,
    boolean sourceVisibilityGenerationGatePassed,
    String sourceVisibilityGenerationStatus,
    boolean sourceRuntimeVisibilitySeparatedFromOfflineGeneration,
    boolean sourceDataGenerationRequiresOfflineDesign,
    boolean sourceRuntimeReloadRequiresFutureBindingDecision,
    boolean gatePassed,
    String gateFailureReason,
    MinecraftResourceReloadArcDecisionStatus decisionStatus,
    MinecraftResourceReloadNextDirection nextDirection,
    boolean resourceReloadArcCompleteForNow,
    boolean resourceReloadImplementationReady,
    boolean resourceReloadProofRecommended,
    boolean currentSteelHookMethodEntryCompatible,
    boolean steelHookPrimitiveDesignRecommendedNow,
    boolean continueResourceReloadAnalysisRecommended,
    boolean registryBootstrapRecommended,
    String recommendedNextConceptId,
    String recommendedNextMilestoneName,
    String recommendedNextPassTitle,
    String nextRecommendedAction,
    List<MinecraftResourceReloadArcDecisionFinding> findings) {
  public MinecraftResourceReloadArcDecisionAnalysis {
    findings = List.copyOf(findings == null ? List.of() : findings);
  }
}
